table 'Customer Performance'

	column 'Customer ID'
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

	column 'Country'
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column 'Completed Revenue'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: completed_revenue

	column 'Completed Orders'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: completed_orders

	column 'Units Sold'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: units_sold

	column 'Average Order Value'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: average_order_value

	column 'First Order Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: first_order_date

	column 'Last Order Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: last_order_date

	column 'Revenue Rank'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: revenue_rank

	partition 'Customer Performance' = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "\\customer_performance.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"customer_id", type text}, {"country", type text}, {"completed_revenue", type number}, {"completed_orders", Int64.Type}, {"units_sold", Int64.Type}, {"average_order_value", type number}, {"first_order_date", type date}, {"last_order_date", type date}, {"revenue_rank", Int64.Type}})
			in
				#"Changed Types"
