table Reconciliation

	column 'Metric'
		dataType: string
		summarizeBy: none
		sourceColumn: metric

	column 'SQL Value'
		dataType: double
		formatString: #,##0.00
		summarizeBy: none
		sourceColumn: sql_value

	partition 'Reconciliation' = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "\\reconciliation.csv"), [Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"metric", type text}, {"sql_value", type number}})
			in
				#"Changed Types"
