table 'Top Products'

	column 'Stock Code'
		dataType: string
		summarizeBy: none
		sourceColumn: stock_code

	column 'Description'
		dataType: string
		summarizeBy: none
		sourceColumn: description

	column 'Completed Revenue'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: completed_revenue

	column 'Units Sold'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: units_sold

	column 'Completed Orders'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: completed_orders

	column 'Cancelled Units'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: cancelled_units

	column 'Cancellation Value'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: cancellation_value

	column 'Cancelled Orders'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: cancelled_orders

	column 'Unit Cancellation Rate'
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: unit_cancellation_rate

	column 'Revenue Rank'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: revenue_rank

	partition 'Top Products' = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "\\top_products.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"stock_code", type text}, {"description", type text}, {"completed_revenue", type number}, {"units_sold", Int64.Type}, {"completed_orders", Int64.Type}, {"cancelled_units", Int64.Type}, {"cancellation_value", type number}, {"cancelled_orders", Int64.Type}, {"unit_cancellation_rate", type number}, {"revenue_rank", Int64.Type}})
			in
				#"Changed Types"
