table 'Top Countries'

	column 'Country'
		dataType: string
		summarizeBy: none
		sourceColumn: country

	column 'Completed Revenue'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: completed_revenue

	column 'Completed Orders'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: completed_orders

	column 'Units Sold'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: units_sold

	column 'Active Customers'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: active_customers

	column 'Average Order Value'
		dataType: double
		formatString: £#,##0.00
		summarizeBy: none
		sourceColumn: average_order_value

	column 'Revenue Share'
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: revenue_share

	column 'Revenue Rank'
		dataType: int64
		formatString: #,##0
		summarizeBy: none
		sourceColumn: revenue_rank

	partition 'Top Countries' = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataFolder & "\\top_countries.csv"), [Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"country", type text}, {"completed_revenue", type number}, {"completed_orders", Int64.Type}, {"units_sold", Int64.Type}, {"active_customers", Int64.Type}, {"average_order_value", type number}, {"revenue_share", type number}, {"revenue_rank", Int64.Type}})
			in
				#"Changed Types"
